### ISSUE TITLE
Проблема с компиляцией проекта.

### ISSUE THREAD

**Issue by Sepera-okeq** [alex290/qtStatic#1]
**Описание проблемы**
Я выполнил все указания в вашем видео(с учетом этой инструкции) - но появилась проблема.
При компиляции моего проекта у меня выдает почему-то ошибку с tiff
Хотя я не понимаю,что у меня может использоваться в проекте.  Прошу помочь)
Проект обычный дефолтный.
Работаю на Windows 10.
**UP 2: Перерыл форумы,не нашел нормального решения.**

**Лог ошибок:**
 ошибка: cannot find -ltiff
 ошибка: collect2.exe: error: ld returned 1 exit status

**Comment by alex290** [comment]
> **Описание проблемы**
> Я выполнил все указания в вашем видео(с учетом этой инструкции) - но появилась проблема.
> При компиляции моего проекта у меня выдает почему-то ошибку с tiff
> Хотя я не понимаю,что у меня может использоваться в проекте. Прошу помочь)
> Проект обычный дефолтный.
> Работаю на Windows 10.
> **UP 2: Перерыл форумы,не нашел нормального решения.**
> 
> **Лог ошибок:**
> ошибка: cannot find -ltiff
> ошибка: collect2.exe: error: ld returned 1 exit status

Обычно такое вылетает. Когда переносят проект. Я в таком случае создаю новый проект под нужную сборку. И переношу исходники.. Может я и ошибаюсь..

**Comment by alex290** [comment]
https://qna.habr.com/q/802637

**Comment by Sepera-okeq** [comment]
се так и не понял. у меня оно должно посути из коробки быть уже готовым, разве не?

**Comment by Sepera-okeq** [comment]
Можете залить уже скомпиленные под 5.15.0 QT?

**Comment by alex290** [comment]
> Можете залить уже скомпиленные под 5.15.0 QT?

Хорошо на следующей недели попробую.. Он весит 7 гигов.

**Comment by Sepera-okeq** [comment]
Не получилось?(
